export const countryIds = [
    { country_id: 0, country_name: 'Afghanistan' },
    { country_id: 1, country_name: 'Albania' },
    { country_id: 2, country_name: 'Algeria' },
    { country_id: 3, country_name: 'Andorra' },
    { country_id: 4, country_name: 'Angola' },
    { country_id: 5, country_name: 'Antigua and Barbuda' },
    { country_id: 6, country_name: 'Argentina' },
    { country_id: 7, country_name: 'Armenia' },
    { country_id: 8, country_name: 'Australia' },
    { country_id: 9, country_name: 'Austria' },
    { country_id: 10, country_name: 'Azerbaijan' },
    { country_id: 11, country_name: 'Bahamas' },
    { country_id: 12, country_name: 'Bahrain' },
    { country_id: 13, country_name: 'Bangladesh' },
    { country_id: 14, country_name: 'Barbados' },
    { country_id: 15, country_name: 'Belarus' },
    { country_id: 16, country_name: 'Belgium' },
    { country_id: 17, country_name: 'Belize' },
    { country_id: 18, country_name: 'Benin' },
    { country_id: 19, country_name: 'Bhutan' },
    { country_id: 20, country_name: 'Bolivia' },
    { country_id: 21, country_name: 'Bosnia and Herzegovina' },
    { country_id: 22, country_name: 'Botswana' },
    { country_id: 23, country_name: 'Brazil' },
    { country_id: 24, country_name: 'Brunei' },
    { country_id: 25, country_name: 'Bulgaria' },
    { country_id: 26, country_name: 'Burkina Faso' },
    { country_id: 27, country_name: 'Burundi' },
    { country_id: 28, country_name: 'Cabo Verde' },
    { country_id: 29, country_name: 'Cambodia' },
    { country_id: 30, country_name: 'Cameroon' },
    { country_id: 31, country_name: 'Canada' },
    { country_id: 32, country_name: 'Central African Republic' },
    { country_id: 33, country_name: 'Chad' },
    { country_id: 34, country_name: 'Chile' },
    { country_id: 35, country_name: 'China' },
    { country_id: 36, country_name: 'Colombia' },
    { country_id: 37, country_name: 'Comoros' },
    { country_id: 38, country_name: 'Congo (Congo-Brazzaville)' },
    { country_id: 39, country_name: 'Costa Rica' },
    { country_id: 40, country_name: 'Croatia' },
    { country_id: 41, country_name: 'Cuba' },
    { country_id: 42, country_name: 'Cyprus' },
    { country_id: 43, country_name: 'Czech Republic' },
    { country_id: 44, country_name: 'Denmark' },
    { country_id: 45, country_name: 'Djibouti' },
    { country_id: 46, country_name: 'Dominica' },
    { country_id: 47, country_name: 'Dominican Republic' },
    { country_id: 48, country_name: 'Ecuador' },
    { country_id: 49, country_name: 'Egypt' },
    { country_id: 50, country_name: 'El Salvador' },
    { country_id: 51, country_name: 'Equatorial Guinea' },
    { country_id: 52, country_name: 'Eritrea' },
    { country_id: 53, country_name: 'Estonia' },
    { country_id: 54, country_name: 'Eswatini' },
    { country_id: 55, country_name: 'Ethiopia' },
    { country_id: 56, country_name: 'Fiji' },
    { country_id: 57, country_name: 'Finland' },
    { country_id: 58, country_name: 'France' },
    { country_id: 59, country_name: 'Gabon' },
    { country_id: 60, country_name: 'Gambia' },
    { country_id: 61, country_name: 'Georgia' },
    { country_id: 62, country_name: 'Germany' },
    { country_id: 63, country_name: 'Ghana' },
    { country_id: 64, country_name: 'Greece' },
    { country_id: 65, country_name: 'Grenada' },
    { country_id: 66, country_name: 'Guatemala' },
    { country_id: 67, country_name: 'Guinea' },
    { country_id: 68, country_name: 'Guinea-Bissau' },
    { country_id: 69, country_name: 'Guyana' },
    { country_id: 70, country_name: 'Haiti' },
    { country_id: 71, country_name: 'Honduras' },
    { country_id: 72, country_name: 'Hungary' },
    { country_id: 73, country_name: 'Iceland' },
    { country_id: 74, country_name: 'India' },
    { country_id: 75, country_name: 'Indonesia' },
    { country_id: 76, country_name: 'Iran' },
    { country_id: 77, country_name: 'Iraq' },
    { country_id: 78, country_name: 'Ireland' },
    { country_id: 79, country_name: 'Israel' },
    { country_id: 80, country_name: 'Italy' },
    { country_id: 81, country_name: 'Jamaica' },
    { country_id: 82, country_name: 'Japan' },
    { country_id: 83, country_name: 'Jordan' },
    { country_id: 84, country_name: 'Kazakhstan' },
    { country_id: 85, country_name: 'Kenya' },
    { country_id: 86, country_name: 'Kiribati' },
    { country_id: 87, country_name: 'Kuwait' },
    { country_id: 88, country_name: 'Kyrgyzstan' },
    { country_id: 89, country_name: 'Laos' },
    { country_id: 90, country_name: 'Latvia' },
    { country_id: 91, country_name: 'Lebanon' },
    { country_id: 92, country_name: 'Lesotho' },
    { country_id: 93, country_name: 'Liberia' },
    { country_id: 94, country_name: 'Libya' },
    { country_id: 95, country_name: 'Liechtenstein' },
    { country_id: 96, country_name: 'Lithuania' },
    { country_id: 97, country_name: 'Luxembourg' },
    { country_id: 98, country_name: 'Madagascar' },
    { country_id: 99, country_name: 'Malawi' },
    { country_id: 100, country_name: 'Malaysia' },
    { country_id: 101, country_name: 'Maldives' },
    { country_id: 102, country_name: 'Mali' },
    { country_id: 103, country_name: 'Malta' },
    { country_id: 104, country_name: 'Marshall Islands' },
    { country_id: 105, country_name: 'Mauritania' },
    { country_id: 106, country_name: 'Mauritius' },
    { country_id: 107, country_name: 'Mexico' },
    { country_id: 108, country_name: 'Micronesia' },
    { country_id: 109, country_name: 'Moldova' },
    { country_id: 110, country_name: 'Monaco' },
    { country_id: 111, country_name: 'Mongolia' },
    { country_id: 112, country_name: 'Montenegro' },
    { country_id: 113, country_name: 'Morocco' },
    { country_id: 114, country_name: 'Mozambique' },
    { country_id: 115, country_name: 'Myanmar' },
    { country_id: 116, country_name: 'Namibia' },
    { country_id: 117, country_name: 'Nauru' },
    { country_id: 118, country_name: 'Nepal' },
    { country_id: 119, country_name: 'Netherlands' },
    { country_id: 120, country_name: 'New Zealand' },
    { country_id: 121, country_name: 'Nigeria' },
    { country_id: 122, country_name: 'North Korea' },
    { country_id: 123, country_name: 'Norway' },
    { country_id: 124, country_name: 'United Kingdom' },
    { country_id: 125, country_name: 'United States' },
    { country_id: 126, country_name: 'Venezuela' },
    { country_id: 127, country_name: 'Vietnam' },
    { country_id: 128, country_name: 'Yemen' },
    { country_id: 129, country_name: 'Zambia' },
    { country_id: 130, country_name: 'Zimbabwe' }
]